version: '3.8'

services:
  postgres_olap:
    image: postgres:15
    environment:
      POSTGRES_DB: olap_db
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    restart: always

  airflow-init:
    image: apache/airflow:2.8.0
    depends_on:
      - postgres_olap
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres_olap/olap_db
    volumes:
      - ./dags:/opt/airflow/dags
      - ./requirements.txt:/opt/airflow/requirements.txt
    entrypoint: /bin/bash
    command: >
      -c "pip install -r /opt/airflow/requirements.txt &&
          airflow db init &&
          airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com"
    restart: "no"

  airflow:
    image: apache/airflow:2.8.0
    depends_on:
      - postgres_olap
      - airflow-init
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres_olap/olap_db
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./requirements.txt:/opt/airflow/requirements.txt
      - ./dags/sql:/opt/airflow/dags/sql
      - ./data:/opt/airflow/data
    ports:
      - "8081:8080"
    command: >
      bash -c "pip install -r /opt/airflow/requirements.txt &&
               airflow webserver & airflow scheduler"
    restart: always