server.port=8000
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/reports-realm

spring.datasource.url=jdbc:postgresql://localhost:5434/olap_db
spring.datasource.username=airflow
spring.datasource.password=airflow
spring.datasource.driver-class-name=org.postgresql.Driver
