server.port=8000
#spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/reports-realm
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/reports-realm

clickhouse.url=jdbc:clickhouse://localhost:8123/reports_db
clickhouse.user=default
clickhouse.password=clickhouse123